"use client";

import React from "react";
import { usePinnedChartStore } from "@/store/usePinnedChartStore";
import GenerativeChart from "@/components/ai-insights/GenerativeChart";
import { Pin, Trash2, Sparkles } from "lucide-react";

export default function PinnedChartsPanel() {
  const { pinnedCharts, unpinChart, clearPinnedCharts } = usePinnedChartStore();

  if (pinnedCharts.length === 0) return null;

  return (
    <div className="w-full bg-slate-900/80 border border-purple-500/30 rounded-2xl p-5 shadow-2xl relative overflow-hidden backdrop-blur-md transition-all duration-300">
      {/* Background Ambient Glow */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-purple-600/10 rounded-full filter blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between pb-3 border-b border-purple-500/20 mb-4">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-purple-500/20 text-purple-300 border border-purple-500/30 animate-pulse">
            <Pin className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              Pinned AI Conversational Visuals
              <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/30">
                {pinnedCharts.length} {pinnedCharts.length === 1 ? "Widget" : "Widgets"}
              </span>
            </h3>
            <p className="text-[11px] text-slate-400">
              Custom dynamic charts generated by AI Copilot pinned to your active dashboard canvas.
            </p>
          </div>
        </div>

        <button
          onClick={clearPinnedCharts}
          className="text-xs text-rose-400/80 hover:text-rose-300 flex items-center gap-1 px-3 py-1.5 rounded-lg bg-rose-500/10 hover:bg-rose-500/20 border border-rose-500/20 transition-all cursor-pointer"
        >
          <Trash2 className="w-3.5 h-3.5" />
          Clear All
        </button>
      </div>

      {/* Grid of Pinned Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {pinnedCharts.map((chart) => (
          <div key={chart.id} className="relative group">
            <div className="absolute top-3 right-3 z-20 flex items-center gap-1.5">
              {chart.queryPrompt && (
                <span className="hidden sm:inline-block text-[9px] font-mono text-purple-300/80 bg-black/60 px-2 py-0.5 rounded-full border border-purple-500/20">
                  Prompt: &quot;{chart.queryPrompt}&quot;
                </span>
              )}
              <button
                onClick={() => unpinChart(chart.id)}
                title="Remove from Dashboard"
                className="p-1.5 rounded-lg bg-slate-800/80 hover:bg-rose-500/20 text-slate-400 hover:text-rose-300 border border-slate-700 hover:border-rose-500/30 transition-all cursor-pointer shadow-md"
              >
                <Trash2 className="w-3.5 h-3.5" />
              </button>
            </div>
            <GenerativeChart schema={chart} queryPrompt={chart.queryPrompt} />
          </div>
        ))}
      </div>
    </div>
  );
}
