import os
import secrets
import string

def generate_password(length=24):
    """Generate a secure, random password suitable for services like Postgres/Redis."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    while True:
        password = ''.join(secrets.choice(alphabet) for i in range(length))
        if (any(c.islower() for c in password)
                and any(c.isupper() for c in password)
                and sum(c.isdigit() for c in password) >= 3):
            return password

def generate_hex(length=32):
    """Generate a random hex string suitable for JWT keys or API tokens."""
    return secrets.token_hex(length)

def main():
    print("=" * 60)
    print("SnowPulse Production Secret Generator")
    print("=" * 60)
    print("Copy the values below into your host's secret manager")
    print("(Render/Fly/Railway/GitHub Secrets):\n")

    secrets_dict = {
        "JWT_SECRET_KEY": generate_hex(32),
        "JWT_REFRESH_SECRET_KEY": generate_hex(32),
        "DB_PASSWORD": generate_password(32),
        "REDIS_PASSWORD": generate_password(32),
        "MINIO_ROOT_PASSWORD": generate_password(32),
        "MEILI_MASTER_KEY": generate_hex(24),
        "GRAFANA_PASSWORD": generate_password(24),
        "ENV": "production",
        "ALLOWED_ORIGINS": "https://your-frontend-domain.vercel.app", 
    }

    for key, val in secrets_dict.items():
        print(f"{key}={val}")

    print("\n" + "=" * 60)
    
    # Generate local .env file
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    
    # We write a safe .env file for local dev that uses these secrets, but sets ENV to development
    local_env_content = f"""# ============================================
# SnowPulse Local Configuration
# GENERATED BY generate_secrets.py
# ============================================
ENV=development

# --- Database ---
DB_NAME=snowpulse
DB_USER=postgres
DB_PASSWORD={secrets_dict["DB_PASSWORD"]}
DB_PORT=5432

# --- Redis ---
REDIS_PASSWORD={secrets_dict["REDIS_PASSWORD"]}
REDIS_PORT=6379

# --- MinIO (S3-compatible Object Storage) ---
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD={secrets_dict["MINIO_ROOT_PASSWORD"]}
MINIO_ENDPOINT=minio:9000
MINIO_SECURE=false
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001

# --- Meilisearch (Full-text Search) ---
MEILI_ENV=development
MEILI_MASTER_KEY={secrets_dict["MEILI_MASTER_KEY"]}
MEILI_HOST=http://meilisearch:7700
MEILI_PORT=7700

# --- FastAPI Backend ---
BACKEND_PORT=8000
JWT_SECRET_KEY={secrets_dict["JWT_SECRET_KEY"]}
JWT_REFRESH_SECRET_KEY={secrets_dict["JWT_REFRESH_SECRET_KEY"]}
LOG_LEVEL=debug

# --- AI Services ---
GEMINI_API_KEY=mock
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_PORT=11434

# --- Frontend ---
FRONTEND_PORT=3000
NEXT_PUBLIC_API_URL=http://localhost:8000
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080

# --- Monitoring ---
PROMETHEUS_PORT=9090
GRAFANA_PORT=3001
GRAFANA_PASSWORD={secrets_dict["GRAFANA_PASSWORD"]}

# --- Caddy Reverse Proxy ---
CADDY_HTTP_PORT=80
CADDY_HTTPS_PORT=443
"""
    
    if os.path.exists(env_path):
        print(f"Warning: {env_path} already exists. Overwriting with new secrets...")
        
    with open(env_path, "w") as f:
        f.write(local_env_content)
        
    print(f"✅ Generated new local development environment file at: {env_path}")
    print("⚠️  Ensure .env is listed in your .gitignore!")
    print("=" * 60)

if __name__ == "__main__":
    main()
